[package]
name = "brainf--k"
version = "0.2.0"
authors = ["Shlomo Ballew <gavib18@gmail.com>"]
edition = "2024"

[lib]
name = "brainf_ck"
path = "src/lib.rs"

[[bin]]
name = "bf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
thiserror = "2.0.17"
